services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      REDIS_HOST: redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: pnpm start:dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter_worker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      REDIS_HOST: redis
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: pnpm start:worker

  postgres:
    image: postgres:17-alpine
    container_name: newsletter_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: newsletter_redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  api_node_modules:
  postgres_data:
  redis_data:
